development:
  adapter: postgresql
  database: howdoi_development
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  host: localhost
  api_key: < riot games API key >
production:
  adapter: postgresql
  database: howdoi_production
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  api_key: < riot games API key >